'use client';

import { useEffect, useRef } from 'react';

/**
 * The brightness-unlock engine. Renders a tiny looping HDR white video; when
 * playing, browsers on EDR-capable displays (XDR MacBook Pros etc.) raise the
 * backlight into the HDR headroom, brightening the whole screen.
 *
 * The element must stay technically visible — a display:none or fully
 * transparent video won't engage the HDR pipeline. 2×2 px at low opacity in a
 * fixed corner is enough.
 *
 * Sources: HEVC/PQ mp4 (Safari) + VP9/HLG webm (Chrome, Firefox). Generated by
 * scripts/generate-hdr-video.sh.
 */
export default function BrightnessUnlocker({ enabled }: { enabled: boolean }) {
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    if (enabled) {
      // play() can reject (e.g. autoplay policy); the button click that set
      // `enabled` counts as a user gesture, so this normally succeeds.
      video.play().catch(() => {});
    } else {
      video.pause();
    }
  }, [enabled]);

  return (
    <video
      ref={videoRef}
      muted
      loop
      playsInline
      preload="auto"
      aria-hidden="true"
      style={{
        position: 'fixed',
        bottom: 0,
        right: 0,
        width: 2,
        height: 2,
        opacity: 0.05,
        pointerEvents: 'none',
        zIndex: 1,
      }}
    >
      {/* Safari picks the HEVC/PQ mp4; Chrome/Firefox the VP9/HLG webm. */}
      <source src="/hdr/white-pq.mp4" type="video/mp4; codecs=hvc1" />
      <source src="/hdr/white-hlg.webm" type="video/webm" />
    </video>
  );
}
