'use client';

import { useEffect, useRef, useState } from 'react';

export interface UnlockerState {
  playing: boolean;
  source: string;
  error: string | null;
}

/**
 * The brightness-unlock engine.
 *
 * Why a fullscreen blended video (and not a hidden one): when HDR content is
 * on screen, macOS raises the backlight but *compensates SDR pixels downward*,
 * so ordinary content keeps the same apparent brightness — a hidden HDR video
 * visibly does nothing. Instead we cover the viewport with an EDR-white video
 * and composite it with `mix-blend-mode: multiply`: result = page × EDR-white,
 * which lifts the page's own pixels into EDR range. Only the browser window
 * gets brighter — a web page can't brighten other apps; that's what the native
 * app is for.
 *
 * Sources: HEVC/PQ mp4 (Safari) + VP9/HLG webm (Chrome, Firefox). Generated by
 * scripts/generate-hdr-video.sh.
 */
export default function BrightnessUnlocker({
  enabled,
  onStateChange,
}: {
  enabled: boolean;
  onStateChange?: (state: UnlockerState) => void;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const report = () =>
      onStateChange?.({
        playing: !video.paused && !video.ended,
        source: video.currentSrc.split('/').pop() ?? '',
        error,
      });

    if (enabled) {
      video
        .play()
        .then(() => {
          setError(null);
          report();
        })
        .catch((e: unknown) => {
          setError(e instanceof Error ? e.message : 'play() failed');
          report();
        });
    } else {
      video.pause();
      report();
    }
  }, [enabled, error, onStateChange]);

  return (
    <video
      ref={videoRef}
      muted
      loop
      playsInline
      preload="auto"
      aria-hidden="true"
      onError={() => setError('video failed to load — codec unsupported?')}
      style={{
        position: 'fixed',
        inset: 0,
        width: '100vw',
        height: '100vh',
        objectFit: 'cover',
        // Multiply page pixels into the EDR-white video: page × white(>1.0)
        // = the page itself, boosted into HDR headroom.
        mixBlendMode: 'multiply',
        pointerEvents: 'none',
        zIndex: 9999,
        // Hide entirely when off so there's no idle compositing cost.
        display: enabled ? 'block' : 'none',
      }}
    >
      {/* Safari picks the HEVC/PQ mp4; Chrome/Firefox the VP9/HLG webm. */}
      <source src="/hdr/white-pq.mp4" type="video/mp4; codecs=hvc1" />
      <source src="/hdr/white-hlg.webm" type="video/webm" />
    </video>
  );
}
